{
 "title": "Time Warner Cable",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "SNR (5th percentile)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       { "params": [ "5" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average SNR",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNR (95th percentile)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Bonded Channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "downstreamBonded",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Bonded Channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstreamBonded",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "dBmV" }
   ],
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 } },
  {
   "title": "Immediate Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "frequency" ], "type": "tag" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "snr" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Immediate Downstream power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "frequency" ], "type": "tag" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "snr" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Immediate Upstream power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "frequency" ], "type": "tag" }
     ],
     "measurement": "upstream",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNR Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Bonded Channels",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstreamBonded",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Bonded Channels",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstreamBonded",
     "select": [
      [
       { "params": [ "number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uncorrectables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "uncorrected" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "SNR" }
   ],
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Correctables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "corrected" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream SNR - Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "SNR" }
   ],
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Noise Floor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "dBmV" }
   ],
   "targets": [
    {
     "alias": "$tag_frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream",
     "select": [
      [
       { "params": [ "noise" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  }
 ]
}